import { useEffect, useReducer, useRef, useState, type Dispatch } from 'react';
import { ArrowRight, ArrowLeft, BookOpen, Check, Compass, Footprints, Gift, Heart, Home, Lightbulb, Mail, Newspaper, Plus, RotateCcw, Settings, ShieldCheck, Sparkles, Wallet, X } from 'lucide-react';
import { createFamily, familyReducer, available, balance, canPublish, issueRecords, DEMO_DAY, type Family, type FamilyAction, type Discovery, type Photo, type Issue, type Reward } from './family';
import { Button, Heading, Tag, Empty, PhotoPicker, dateText, now, photoSrc, timeText } from './ui';
import { Quest, topics, type Topic, type QuestResult } from './Quest';
type Role='child'|'parent'|'grand';
type Props={state:Family;dispatch:Dispatch<FamilyAction>};
const roles={child:{name:'子ども',person:'はる',job:'発見して、ためる',icon:Compass},parent:{name:'親',person:'おうちの人',job:'承認と、ふたりの見守り',icon:ShieldCheck},grand:{name:'祖父母',person:'おばあちゃん',job:'歩く、伝える、孫を読む',icon:Heart}};
const rewardPresets:[string,Reward['kind'],string][]=[['今月のおこづかい500円','once','今月1回。交換したら、おうちの人から受け取る。'],['毎月のおこづかい108円アップ','monthly','10月からずっと。見直すときは、親子で相談してから。'],['ディズニーに行く券','experience','日程と予算は親子で相談。予約はおうちの人と一緒に。'],['自分で考える','experience','']];
const exchangeLabels={none:'まだ交換していません',pending:'交換をお願いしています',held:'親子で相談中',planned:'ごほうびの約束ができました',given:'おうちの人が渡したと記録しました',received:'受け取りを確認しました'};
function DiscoveryCard({record,onOpen,showPoints=true}:{record:Discovery;onOpen:()=>void;showPoints?:boolean}){
 return <button className={'discovery-card '+(!record.photo?'words-card':'')} onClick={onOpen}>
 {record.photo?<img src={photoSrc(record.photo)} alt={record.photo.alt}/>:<div className="words-cover"><span>MY DISCOVERY</span><b>「{record.reason}」</b><BookOpen size={24}/></div>}
 <div className="discovery-body"><small>{dateText(record.date)} · 発見 #{record.id.replace('past-','')}</small><h3>{record.title}</h3>{showPoints&&<Tag tone={record.points==='approved'?'green':'amber'}>{record.points==='approved'?'親が確認した発見':record.points==='private'?'自分だけの発見':record.points==='held'?'親子で相談中':'5ptの確認待ち'}</Tag>}<span className="open-record">開く <ArrowRight size={16}/></span></div></button>;
}
function RecordDetail({record,role,dispatch,onClose}:{record:Discovery;role:Role;dispatch:Dispatch<FamilyAction>;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);
 return <dialog ref={ref} className="detail-dialog" onCancel={onClose}><div className="dialog-top"><Tag>発見の原本 · 第{record.revision}版</Tag><button className="icon-btn" aria-label="閉じる" onClick={onClose}><X/></button></div>
 {record.photo&&<img className="detail-photo" src={photoSrc(record.photo)} alt={record.photo.alt}/>}<small>{dateText(record.date)}</small><h2>{record.title}</h2>{record.prediction&&<p>最初の予想：{record.prediction}</p>}{record.choice&&<p>調べたこと・選んだこと：{record.choice}</p>}<blockquote>{record.reason}</blockquote>
 {role!=='grand'&&<><p>ポイント：{record.points==='approved'?'確認済み':record.points==='private'?'未申請':record.points==='held'?'保留中':'5ptの確認待ち'}</p><p>祖父母への共有：{record.share==='approved'?'親の確認済み':record.share==='private'?'共有しない':record.share==='held'?'保留中':'親の確認待ち'}</p></>}
 {role==='child'&&record.share!=='private'&&<Button secondary onClick={()=>{dispatch({type:'revoke',id:record.id});onClose()}}>祖父母への共有を取り消す</Button>}
 {role==='child'&&record.points==='private'&&<Button onClick={()=>{dispatch({type:'apply',id:record.id,share:false});onClose()}}>この記録を親に見せて5ptをお願いする</Button>}<Button secondary onClick={onClose}>戻る</Button></dialog>;
}
function Paper({records,title,number='プレビュー',onOpen}:{records:Discovery[];title:string;number?:string;onOpen:(r:Discovery)=>void}){
 return <article className="family-paper"><div className="paper-topline"><span>はるから、おばあちゃんへ</span><span>{number}</span></div><h2>{title}</h2><div className="paper-rule">くらしの中の「なんで？」を、家族の思い出に。</div><div className="paper-stories">{records.map((r,i)=><section className={i===0?'lead-story':'small-story'} key={r.id}>{r.photo&&<img src={photoSrc(r.photo)} alt={r.photo.alt}/>}<small>{dateText(r.date)} / はるの発見</small><h3>{r.title}</h3><blockquote>「{r.reason}」</blockquote><button className="text-btn" onClick={()=>onOpen(r)}>この日の記録を開く <ArrowRight size={15}/></button></section>)}</div><footer>本人の言葉をそのままに。家族だけの発見だより。</footer></article>;
}
function StepSummary({state,forParent=false}:{state:Family;forParent?:boolean}){
 const s=state.steps;if(forParent&&!s.shared)return <div className="step-summary"><Footprints/><p>歩数は共有していません</p></div>;
 return <div className="step-summary"><div className="section-title"><span><Footprints size={22}/> {s.date===DEMO_DAY?'今日の歩数':'前日の歩数'}</span><Tag>デモ</Tag></div>{s.count===null?<h3>まだ取得できていません</h3>:<div className="step-number-large">{s.count.toLocaleString()}<small>歩</small></div>}<small>{s.date} · {s.source}<br/>歩数の更新：{timeText(s.updatedAt)}</small></div>;
}
function Welfare({state}:{state:Family}){return <section className="panel welfare-card"><div className="section-title"><Tag>祖父母の見守り</Tag><Heart size={22}/></div><h2>おばあちゃんから</h2>{state.checkin?<><p className="checkin-message">「元気だよ」</p><p>本人が押した日時<br/><b>{timeText(state.checkin.at)}</b></p>{state.checkin.text&&<blockquote>{state.checkin.text}</blockquote>}{state.checkin.photo&&<img className="status-photo" src={photoSrc(state.checkin.photo)} alt={state.checkin.photo.alt}/>}</>:<p>まだ安否連絡は届いていません。</p>}<StepSummary state={state} forParent/><small>本人からの連絡と、共有された歩数です。体調の自動判定はしません。</small></section>}
function WalletView({state,dispatch,parent=false}:{parent?:boolean}&Props){
 const [editing,setEditing]=useState(false);const [title,setTitle]=useState(state.reward.title);const [cost,setCost]=useState(state.reward.cost);const [terms,setTerms]=useState(state.reward.terms);const [kind,setKind]=useState<Reward['kind']>(state.reward.kind);
 const r=state.reward;const at=()=>now();
 return <><Heading kicker={parent?'親子の約束':'はるのおこづかい'} title={parent?'発見の先に、楽しみを。':'ためたら、何をしたい？'} sub={parent?'ごほうびの内容と条件を、親子で決めます。':'お金でも、お出かけでも。きみから提案してみよう。'}/>
 <div className="wallet-layout"><section className="wallet-balance"><Wallet size={30}/><p>今つかえるポイント</p><strong data-testid="wallet-balance">{available(state)}<span>pt</span></strong><p>持っているポイント {balance(state)}pt{['pending','held'].includes(state.exchange)&&'（交換用に'+r.cost+'ptを確保中）'}</p><div className="goal-track"><span style={{width:Math.min(100,available(state)/r.cost*100)+'%'}}/></div><p>{Math.max(0,r.cost-available(state))>0?'目標まで、あと'+Math.max(0,r.cost-available(state))+'pt':'目標に届いたよ！'}</p><small>親子の約束：調べて自分の考えを残すと、親の確認で5pt。写真や正解は条件ではありません。</small></section>
 <section className="panel reward-card"><Tag tone={r.status==='approved'?'green':'amber'}>{r.status==='approved'?'親子で決めた目標':r.status==='pending'?'ごほうびの提案・親の確認待ち':'ごほうびの提案・相談中'}</Tag><Gift size={34}/><h2>{r.title}</h2><p className="reward-price">{r.cost}ptで交換</p><p>{r.terms}</p>{r.kind==='monthly'&&<p className="quiet">1回の交換で、続ける約束。毎月ポイントを消費する仕組みではありません。</p>}
 {parent&&r.status!=='approved'&&<div className="actions"><Button onClick={()=>dispatch({type:'reviewReward',approve:true})}>このごほうび・条件を承認する</Button><Button secondary onClick={()=>dispatch({type:'reviewReward',approve:false})}>親子で相談する</Button></div>}
 {state.exchange==='none'&&!parent&&<><Button disabled={r.status!=='approved'||available(state)<r.cost} onClick={()=>dispatch({type:'exchange',op:'request',at:at()})}>このごほうびへの交換をお願いする</Button><button className="text-btn" onClick={()=>setEditing(!editing)}><Plus size={17}/>自分のごほうびを提案する</button></>}
 {state.exchange!=='none'&&<div className="exchange-status" role="status"><Check size={20}/><b>{exchangeLabels[state.exchange]}</b></div>}
 {['pending','held'].includes(state.exchange)&&(parent?<div className="actions"><Button onClick={()=>dispatch({type:'exchange',op:'approve',at:at()})}>{r.cost}ptの交換を承認する</Button><Button secondary onClick={()=>dispatch({type:'exchange',op:'hold',at:at()})}>いったん保留する</Button><button className="text-btn" onClick={()=>dispatch({type:'exchange',op:'cancel',at:at()})}>今回は取り消してポイントを戻す</button></div>:<Button secondary onClick={()=>dispatch({type:'exchange',op:'cancel',at:at()})}>交換のお願いを取り消す</Button>)}
 {parent&&state.exchange==='planned'&&<Button onClick={()=>dispatch({type:'exchange',op:'give',at:at()})}>{r.kind==='once'?'渡したと記録する':'約束を実行したと記録する'}</Button>}
 {!parent&&state.exchange==='given'&&<Button onClick={()=>dispatch({type:'exchange',op:'receive',at:at()})}>受け取った・体験したと確認する</Button>}<small>実際の送金・予約は行いません。金額とptは発表用の例です。</small></section></div>
 {editing&&!parent&&state.exchange==='none'&&<section className="panel proposal"><h2>こんなごほうびはどうかな？</h2><div className="preset-grid">{rewardPresets.map(([name,k,t])=><button key={name} onClick={()=>{setTitle(name==='自分で考える'?'':name);setKind(k);setTerms(t)}}><Gift size={20}/>{name}</button>)}</div><div className="form-grid"><label className="field">ほしいごほうび<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80}/></label><label className="field">何ptを目指す？<input type="number" min="1" max="10000" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label></div><label className="field">いつ・どのくらい続く？ 親子で決めたい条件<textarea value={terms} maxLength={240} onChange={e=>setTerms(e.target.value)} placeholder="例：10月からずっと。変えるときは一緒に相談する。"/></label><Button disabled={!title.trim()||!terms.trim()||!Number.isInteger(cost)||cost<1||cost>10000} onClick={()=>{dispatch({type:'proposeReward',title,cost,kind,terms});setEditing(false)}}>このごほうびを親に提案する</Button><small>親が承認するまでは交換できません。内容を変えたら、もう一度確認してもらいます。</small></section>}
 <section className="panel ledger"><h2>ポイントの足あと</h2>{[...state.ledger].reverse().map(l=><div key={l.id}><span><small>{dateText(l.at)}</small><b>{l.label}</b></span><strong>{l.amount>0?'+':''}{l.amount}pt</strong></div>)}</section></>;
}
function RecordForm({result,dispatch,onSaved,onBack}:{result:QuestResult;dispatch:Dispatch<FamilyAction>;onSaved:(applied:boolean)=>void;onBack:()=>void}){
 const [reason,setReason]=useState('');const [photo,setPhoto]=useState<Photo>(null);const [share,setShare]=useState(false);const [review,setReview]=useState(false);const id=useRef('discovery-'+Date.now());
 const save=(apply:boolean)=>{dispatch({type:'record',id:id.current,title:result.title,reason,photo,date:now(),apply,share,prediction:result.prediction,choice:result.choice});onSaved(apply)};
 return <><button className="text-btn" onClick={review?()=>setReview(false):onBack}><ArrowLeft size={16}/>戻る</button><Heading kicker="最後のひとつ" title={review?'親に見せる内容は、これでいい？':'今日の発見を、自分の言葉で。'} sub="短くてOK。まだ分からないことも、きみの発見だよ。"/><div className="record-layout"><section className="panel"><Tag>{result.title}</Tag><p>調べたこと：{result.choice}</p>{!review?<><label className="field">{result.hint}<textarea value={reason} maxLength={280} onChange={e=>setReason(e.target.value)} placeholder="やってみて気づいたこと、次に知りたいことを書こう。"/></label><PhotoPicker value={photo} onChange={setPhoto}/><Button disabled={!reason.trim()} onClick={()=>setReview(true)}>内容を確認する</Button></>:<>{photo&&<img className="review-photo" src={photoSrc(photo)} alt={photo.alt}/>}<blockquote>{reason}</blockquote><label className="check-row"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/>この記録を、おばあちゃんへの新聞にも載せていい</label><p className="quiet">チェックしなくてもポイントは同じ。新聞は親が確認してから届きます。</p><Button onClick={()=>save(true)}>親に見せて、5ptをお願いする</Button><Button secondary onClick={()=>save(false)}>誰にも見せず、自分の発見帳に残す</Button></>}</section><aside className="panel record-promise"><BookOpen size={32}/><h2>発見が、<br/>きみの一冊になる。</h2><p>今日の言葉と写真が、発見帳にたまっていく。</p><p>選んだ記録は新聞になって、家族にも届くよ。</p><div className="point-stamp">親の確認で <b>+5pt</b></div><small>写真をつけても、つけなくても同じ。祖父母への共有も自由です。</small></aside></div></>;
}
function ParentHome({state,dispatch,onWallet,onPaper,onOpen}:Props&{onWallet:()=>void;onPaper:()=>void;onOpen:(r:Discovery)=>void}){
 const pending=state.records.filter(r=>['pending','held'].includes(r.points)||['pending','held'].includes(r.share));
 return <><Heading kicker="家族の見守り" title="はるの発見も、おばあちゃんの今日も。" sub="子どもには承認を。祖父母には、届いた声の確認を。"/><div className="parent-layout"><div><div className="section-title"><h2>はるの発見</h2><Tag>{pending.length}件の確認</Tag></div>
 {!pending.length&&<div className="panel"><Check size={28}/><h3>発見の確認は終わっています。</h3><p>次は、ごほうびや新聞を確認できます。</p><div className="actions"><Button onClick={onWallet}>おこづかい・ごほうびへ</Button><Button secondary onClick={onPaper}>新聞を届ける</Button></div></div>}
 {pending.map(r=><section key={r.id} className="panel approval"><div className="approval-record">{r.photo&&<img src={photoSrc(r.photo)} alt={r.photo.alt}/>}<div><small>{dateText(r.date)} / 本人の言葉</small><h2>{r.title}</h2><blockquote>{r.reason}</blockquote><button className="text-btn" onClick={()=>onOpen(r)}>予想・選んだことも見る</button></div></div>
 <div className="approval-action"><h3>① 発見ポイント</h3><p>約束：調べて、自分の考えを残す。正解・写真・共有の有無では採点しません。</p>{r.points==='approved'?<Tag tone="green">+5pt 承認済み</Tag>:<div className="actions"><Button onClick={()=>dispatch({type:'points',id:r.id,approve:true})}>5ptを承認する</Button><Button secondary onClick={()=>dispatch({type:'points',id:r.id,approve:false})}>ポイントを保留する</Button></div>}</div>
 <div className="approval-action"><h3>② おばあちゃんへの共有</h3>{r.share==='private'?<p>本人が共有を選んでいません。新聞には載せません。</p>:r.share==='approved'?<Tag tone="green">この内容・宛先で確認済み</Tag>:<><p>本人の共有意思あり。宛先：おばあちゃん／この記録の第{r.revision}版。</p><div className="actions"><Button secondary onClick={()=>dispatch({type:'sharing',id:r.id,approve:true})}>この内容の新聞掲載を認める</Button><button className="text-btn" onClick={()=>dispatch({type:'sharing',id:r.id,approve:false})}>掲載を保留する</button></div></>}</div></section>)}
 <div className="parent-links"><button onClick={onWallet}><Gift/><span><b>ごほうび・おこづかい</b><small>{state.reward.status==='pending'?'はるから、新しいごほうびの提案':exchangeLabels[state.exchange]}</small></span><ArrowRight/></button><button onClick={onPaper}><Newspaper/><span><b>たまった発見を、新聞に</b><small>許可された記録から、おたよりを作る</small></span><ArrowRight/></button></div></div><Welfare state={state}/></div></>;
}
function NewspaperView({state,dispatch,role,onOpen,archive=false}:Props&{role:Role;onOpen:(r:Discovery)=>void;archive?:boolean}){
 const eligible=state.records.filter(canPublish);const [selected,setSelected]=useState<string[]>(eligible.map(r=>r.id));const [title,setTitle]=useState('くらしの発見だより');const [preview,setPreview]=useState(false);const [active,setActive]=useState<string|null>(null);const [reply,setReply]=useState('');const [sent,setSent]=useState(false);
 const visible=state.issues.filter(i=>issueRecords(state,i).length);const issue=visible.find(i=>i.id===active)??(role==='grand'&&!archive?visible.at(-1):undefined);
 const materials=eligible.filter(r=>selected.includes(r.id));
 return <><Heading kicker={role==='parent'?'家族の編集室':role==='grand'?'はるから届く新聞':'家族のアルバム'} title={role==='parent'&&!archive?'たまった発見を、届けよう。':archive?'いつでも開ける、家族の思い出。':'はるの「なんで？」が届きました。'} sub={role==='parent'?'本人が共有を選び、親が確認した記録だけを掲載します。':'一つひとつの発見が、家族の一冊になっていきます。'}/>
 {role==='parent'&&!archive&&<><div className="editor-toolbar"><label>新聞の名前<input value={title} maxLength={50} onChange={e=>{setTitle(e.target.value);setPreview(false)}}/></label><span>宛先：おばあちゃん</span><Tag>{materials.length}件の記事</Tag></div><div className="material-list">{state.records.filter(r=>r.points!=='private').map(r=><label key={r.id} className={!canPublish(r)?'unavailable':''}><input type="checkbox" disabled={!canPublish(r)} checked={canPublish(r)&&selected.includes(r.id)} onChange={e=>{setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id));setPreview(false)}}/><span>{r.title}<small>{canPublish(r)?'共有確認済み':r.share==='private'?'本人が共有しない選択':'掲載は親の確認待ち'}</small></span></label>)}</div>
 {!preview?<Button disabled={!materials.length||!title.trim()} onClick={()=>setPreview(true)}>この記録で新聞を作ってみる</Button>:<><Paper records={materials} title={title} onOpen={onOpen}/><div className="publish-bar"><p><b>この紙面を、おばあちゃんへ。</b><br/>ポイントやおこづかい残高は載りません。</p><Button disabled={state.issues.some(i=>i.title===title.trim()&&JSON.stringify(i.materials)===JSON.stringify(materials.map(r=>({id:r.id,revision:r.revision}))))} onClick={()=>{dispatch({type:'publish',ids:materials.map(r=>r.id),title,at:now()});setSent(true)}}>この内容で新聞を届ける <Mail size={18}/></Button></div>{sent&&<div className="success-banner" role="status"><Check/>おばあちゃんのおたよりに届きました。アルバムにも残りました。（デモ内）</div>}</>}</>}
 {(role!=='parent'||archive)&&(!visible.length?<Empty title="新聞は、まだ届いていません。"><p>記録がたまったら、親が選んで届けます。返信はいつでも自由です。</p></Empty>:<><div className="issue-tabs">{visible.map((i,index)=><button key={i.id} className={issue?.id===i.id?'selected':''} onClick={()=>setActive(i.id)}><Newspaper size={22}/><span><b>第{index+1}号 · {i.title}</b><small>{dateText(i.at)} · {issueRecords(state,i).length}つの発見</small></span><ArrowRight size={18}/></button>)}</div>{issue&&<><Paper records={issueRecords(state,issue)} title={issue.title} number={'第'+(state.issues.indexOf(issue)+1)+'号'} onOpen={onOpen}/>{role==='grand'&&<section className="panel reply-panel"><h2>はるへ、ひとこと。</h2><p>自分の経験や、気になったことを。読むだけでも大丈夫。</p>{state.replies.find(r=>r.issueId===issue.id)?<div className="success-banner"><Check/>返信を届けました：「{state.replies.find(r=>r.issueId===issue.id)?.text}」</div>:<><div className="chips">{['昔は、今とは電気の使い方が違ったよ。','どうしてそう思ったの？','自分で調べて考えたんだね。'].map(t=><button key={t} onClick={()=>setReply(t)}>{t}</button>)}</div><label className="field">家族からの言葉<textarea value={reply} maxLength={200} onChange={e=>setReply(e.target.value)}/></label><Button disabled={!reply.trim()} onClick={()=>dispatch({type:'reply',issueId:issue.id,text:reply,at:now()})}>はるに返信する</Button><small>返信しなくても、はるの探検は続きます。</small></>}</section>}</>}</>)}
 </>;
}
function GrandHome({state,dispatch,onRead}:Props&{onRead:()=>void}){
 const [details,setDetails]=useState(false);const [text,setText]=useState(state.checkin?.text??'');const [photo,setPhoto]=useState<Photo>(state.checkin?.photo??null);const [updated,setUpdated]=useState(false);const count=state.issues.filter(i=>issueRecords(state,i).length).length;
 return <><Heading kicker="おばあちゃんのホーム" title="今日も、あなたのペースで。" sub="歩数を見て、ひと押し。家族に「元気だよ」が届きます。"/><div className="grand-top"><section className="panel"><StepSummary state={state}/><label className="check-row"><input type="checkbox" checked={state.steps.shared} onChange={e=>dispatch({type:'stepShare',value:e.target.checked})}/>この歩数を親に見せる</label><small>実際の歩数計とは未接続です。</small></section><section className="checkin-card"><Heart size={34}/><h2>家族に、無事を知らせよう。</h2><p>宛先：はるのおうちの人</p><Button onClick={()=>dispatch({type:'checkin',at:now()})}><Heart size={25}/>元気だよ</Button><p role="status">{state.checkin?'親へ伝えました（デモ）':'写真や文章は、いりません。'}</p><small>本人が押した日時：{timeText(state.checkin?.at??null)}</small></section></div>
 <button className="letter-inbox" onClick={onRead}><div className="letter-symbol"><Mail size={42}/></div><span><Tag>{count?count+'通のおたより':'家族のおたより'}</Tag><h2>{count?'はるの発見だよりが届いています。':'はるの新聞を、ここで待っています。'}</h2><p>写真と言葉で、孫の「やってみた」を読む。</p></span><ArrowRight size={30}/></button>
 <button className="text-btn" onClick={()=>setDetails(!details)}>写真・ひとことを添える / 連絡の設定</button>{details&&<section className="panel"><label className="field">今日のひとこと（任意）<textarea value={text} maxLength={180} onChange={e=>setText(e.target.value)}/></label><PhotoPicker value={photo} onChange={setPhoto} sampleEnabled={false}/><Button disabled={!state.checkin} onClick={()=>{dispatch({type:'statusDetail',text,photo});setUpdated(true)}}>連絡に添える</Button>{!state.checkin&&<p>先に「元気だよ」を押すと、ひとことを添えられます。</p>}{updated&&<p role="status">添えた内容を更新しました。</p>}{state.checkin&&<button className="text-btn" onClick={()=>{dispatch({type:'revokeStatus'});setText('');setPhoto(null);setUpdated(false)}}>送った安否連絡を取り消す</button>}</section>}</>;
}
export default function PresentationApp(){
 const [state,dispatch]=useReducer(familyReducer,undefined,createFamily);const [role,setRole]=useState<Role>('child');const [page,setPage]=useState('home');const [topic,setTopic]=useState<Topic>('light');const [question,setQuestion]=useState('');const [result,setResult]=useState<QuestResult|null>(null);const [detail,setDetail]=useState<string|null>(null);const [settings,setSettings]=useState(false);const [large,setLarge]=useState(false);const [reduced,setReduced]=useState(false);const [resetting,setResetting]=useState(false);const [session,setSession]=useState(0);const [notice,setNotice]=useState('');const main=useRef<HTMLElement>(null);
 useEffect(()=>{main.current?.focus();window.scrollTo({top:0,behavior:'instant'})},[role,page]);
 const changeRole=(r:Role)=>{setRole(r);setPage('home');setDetail(null);setNotice('')};
 const navigate=(p:string)=>{setPage(p);setNotice('')};const open=(r:Discovery)=>setDetail(r.id);
 const start=(t:Topic,q='')=>{setTopic(t);setQuestion(q);setPage('quest');setSession(n=>n+1);setNotice('')};
 const reset=()=>{dispatch({type:'reset'});setRole('child');setPage('home');setResult(null);setDetail(null);setQuestion('');setNotice('');setResetting(false);setSession(n=>n+1)};
 const nav=role==='child'?[['home','やってみる',Compass],['album','発見帳',BookOpen],['wallet','おこづかい',Gift]] as const:role==='parent'?[['home','見守り',ShieldCheck],['wallet','ごほうび・承認',Gift],['paper','新聞を届ける',Newspaper],['archive','アルバム',BookOpen]] as const:[['home','ホーム',Home],['paper','おたより',Mail],['archive','思い出',BookOpen]] as const;
 const reply=state.replies.filter(r=>state.issues.some(i=>i.id===r.issueId&&issueRecords(state,i).length)).at(-1);
 const total=available(state);const record=state.records.find(r=>r.id===detail);const PersonIcon=roles[role].icon;
 return <div className={'presentation role-'+role+(large?' large-text':'')+(reduced?' reduce-motion':'')}><a className="skip-link" href="#main">内容へ移動</a><div className="presenter-bar"><span>発表プレビュー <b>架空の家族</b></span><div className="role-switch" aria-label="発表者用の役割切替">{(Object.keys(roles) as Role[]).map(r=><button key={r} aria-pressed={role===r} onClick={()=>changeRole(r)}>{roles[r].name}</button>)}</div><div className="presenter-tools"><button onClick={()=>setSettings(!settings)} aria-label="表示とデモの設定"><Settings size={17}/></button><button onClick={()=>setResetting(true)} aria-label="デモを最初に戻す"><RotateCcw size={17}/></button></div></div>
 {settings&&<div className="settings-panel"><label><input type="checkbox" checked={large} onChange={e=>setLarge(e.target.checked)}/>文字を200%に</label><label><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/>動きを減らす</label><label>歩数のデモ状態<select onChange={e=>dispatch({type:'steps',mode:e.target.value as 'today'|'zero'|'unavailable'|'yesterday'})} defaultValue="today"><option value="today">今日3,240歩</option><option value="zero">今日0歩</option><option value="unavailable">未取得</option><option value="yesterday">前日の値</option></select></label><button onClick={()=>{setRole('child');setResult({title:'電気を5時間つけたら、いくら？',prediction:'10円くらい',choice:'10W・5時間で1.55円（練習）',hint:'時間を変えて、気づいたことは？'});setPage('record');setSession(n=>n+1);setSettings(false)}}>発表の短縮開始（記録から）</button><small>短縮開始は架空の体験済みシーン。記録・承認は自分で操作します。</small></div>}
 {resetting&&<div className="reset-confirm" role="alert"><p>このデモで追加した記録・写真・ポイント・新聞を消し、最初の架空データに戻します。</p><Button onClick={reset}>最初の状態に戻す</Button><Button secondary onClick={()=>setResetting(false)}>戻さない</Button></div>}
 <header className="brand-header"><button className="brand" onClick={()=>navigate('home')}><span className="brand-icon"><Compass size={27}/></span><span>やってみクエスト<small>くらしの「なんで？」を、きみの力に。</small></span></button><div className="identity"><span className="avatar"><PersonIcon size={21}/></span><span><b>{roles[role].person}</b><small>{roles[role].job}</small></span></div></header>
 <div className="app-frame"><aside className="sidebar"><div className="sidebar-caption">{roles[role].name}のメニュー</div><nav aria-label={roles[role].name+'のメニュー'}>{nav.map(([key,label,Icon])=><button key={key} aria-current={page===key?'page':undefined} onClick={()=>navigate(key)}><Icon size={21}/><span>{label}</span></button>)}</nav><div className="sidebar-note"><BookOpen size={25}/><p>発見がたまる。<br/>家族の思い出になる。</p></div><small className="demo-disclosure">発表用のデモです。記録は再読み込みで戻ります。送金・予約・実通知・郵送・外部AI通信は行いません。</small></aside>
 <main id="main" ref={main} tabIndex={-1} className="main-content">{notice&&<div className="success-banner" role="status"><Check/>{notice}</div>}
 {role==='child'&&page==='home'&&<><Heading kicker="こんにちは、はる！" title="今日の「なんで？」を見つけよう。" sub="気になることを調べたら、きみの発見がおこづかいにつながる。"/>
 <div className="child-overview"><section className="quest-hero"><Tag tone="amber">今日のおすすめ探検</Tag><div className="hero-icon"><Lightbulb size={66}/></div><h2>この明かり、<br/>5時間でいくら？</h2><p>いつも使う電気を、お金で見てみよう。</p><div className="hero-bottom"><Button onClick={()=>start('light')}>これを調べてみる <ArrowRight size={20}/></Button><span>親の確認で <b>+5pt</b></span></div></section>
 <button className="goal-preview" onClick={()=>navigate('wallet')}><div className="section-title"><Gift size={24}/><Tag>{state.reward.status==='approved'?'親子の目標':'親に提案中'}</Tag></div><p>いま、ためているのは</p><h2>{state.reward.title}</h2><div className="point-total">{total}<span> / {state.reward.cost}pt</span></div><div className="goal-track"><span style={{width:Math.min(100,total/state.reward.cost*100)+'%'}}/></div><b>{total>=state.reward.cost?'目標に届いた！交換をお願いしよう':'あと'+(state.reward.cost-total)+'ptで目標に届く！'}</b><span className="goal-link">自分のごほうびを考える <ArrowRight size={17}/></span></button></div>
 <div className="section-title"><h2>ほかにも、気になる？</h2><small>好きな探検を選んでOK</small></div><div className="topic-grid">{(['bill','drink','own'] as Topic[]).map(k=>{const Icon=topics[k].icon;return <button key={k} onClick={()=>start(k)}><Icon size={28}/><span><b>{k==='own'?'自分の「なんで？」を書く':topics[k].title}</b><small>{k==='bill'?'先月と比べてみよう':k==='drink'?'値段と量、何を大切にする？':'思いついたことから始めよう'}</small></span><ArrowRight size={18}/></button>})}</div>
 {reply&&<section className="family-seed"><Mail/><div><b>おばあちゃんから、新聞への返事</b><p>「{reply.text}」</p><button className="text-btn" onClick={()=>{dispatch({type:'next',title:'昔と今で、電気の使い方はどう違う？',source:reply.issueId+'への祖父母の返信'});start('own','昔と今で、電気の使い方はどう違う？')}}>この話から、次の「なんで？」へ</button><small>使わずに別の探検を選んでもいいよ。</small></div></section>}
 <div className="section-title"><h2>はるの発見帳 <span>{state.records.length}</span></h2><button className="text-btn" onClick={()=>navigate('album')}>全部見る <ArrowRight size={15}/></button></div><div className="discovery-grid compact-grid">{[...state.records].reverse().slice(0,3).map(r=><DiscoveryCard key={r.id} record={r} onOpen={()=>open(r)}/>)}</div></>}
 {role==='child'&&page==='quest'&&<Quest key={session} topic={topic} question={question} onBack={()=>navigate('home')} onDone={r=>{setResult(r);setPage('record')}}/>}
 {role==='child'&&page==='record'&&result&&<RecordForm key={session} result={result} dispatch={dispatch} onBack={()=>navigate('home')} onSaved={applied=>{setPage('album');setNotice(applied?'発見帳に、新しい記録が増えたよ。親に5ptをお願いしました。':'自分だけの発見帳に残したよ。親にもおばあちゃんにも見えていません。')}}/>}
 {role==='child'&&page==='album'&&<><Heading kicker="はるの発見帳" title="やってみたことが、たまっていく。" sub="写真がある日も、言葉だけの日も。きみの発見が、ここに。" action={<Button secondary onClick={()=>navigate('archive')}><Newspaper size={19}/>新聞アルバム</Button>}/><div className="album-count"><b>{state.records.length}</b>つの発見 <span>{state.issues.filter(i=>issueRecords(state,i).length).length}通の新聞</span></div><div className="discovery-grid">{[...state.records].reverse().map(r=><DiscoveryCard key={r.id} record={r} onOpen={()=>open(r)}/>)}</div></>}
 {page==='wallet'&&role!=='grand'&&<WalletView key={role} state={state} dispatch={dispatch} parent={role==='parent'}/>}
 {role==='parent'&&page==='home'&&<ParentHome state={state} dispatch={dispatch} onWallet={()=>navigate('wallet')} onPaper={()=>navigate('paper')} onOpen={open}/>}
 {role==='grand'&&page==='home'&&<GrandHome state={state} dispatch={dispatch} onRead={()=>navigate('paper')}/>}
 {(page==='paper'||page==='archive')&&<NewspaperView key={role+page} state={state} dispatch={dispatch} role={role} onOpen={open} archive={page==='archive'}/>}
 <footer className="app-footer">YATTEMI QUEST <span>自分で見つける。家族でつながる。</span></footer></main></div>
 {record&&<RecordDetail key={record.id} record={record} role={role} dispatch={dispatch} onClose={()=>setDetail(null)}/>}</div>;
}
