import { useState } from 'react';
import { ArrowLeft, Lightbulb, Check, Sparkles, ShoppingBag, Search, Zap } from 'lucide-react';
import { Button, Heading, Tag } from './ui';
import { electricityCost } from './quest-model';
export type Topic='light'|'bill'|'drink'|'own';
export type QuestResult={title:string;prediction:string;choice:string;hint:string};
export const topics={
 light:{title:'電気をつけたら、いくら？',lead:'寝るまでつけている、この明かり。5時間で何円くらいだと思う？',icon:Lightbulb,steps:['電球の「W」を、おうちの人と見つける','つける時間を変えて、金額を比べる','予想と違ったことを一つ残す']},
 bill:{title:'今月の電気代はいくら？',lead:'家で使う電気は、ひと月でいくらになるんだろう。',icon:Zap,steps:['おうちの人に「電気代を一緒に見たい」と聞く','今月と先月の金額を見つける','違いと、気になった理由を残す']},
 drink:{title:'300円で、何を選ぶ？',lead:'小さい飲み物と、大きい飲み物。値段だけで決めていいのかな？',icon:ShoppingBag,steps:['どちらを選びたいか、まず予想する','値段と量をそろえて比べる','選んだものと、その理由を残す']},
 own:{title:'自分の「なんで？」を調べる',lead:'ふだんの生活で、ちょっと気になったことから。',icon:Search,steps:['何を知りたいか、一つにしぼる','おうちの人と、調べられるものを一つ探す','見つけたことと、自分の考えを残す']},
};
export function Quest({topic:initial,question:initialQuestion='',onDone,onBack}:{topic:Topic;question?:string;onDone:(r:QuestResult)=>void;onBack:()=>void}){
 const [topic,setTopic]=useState(initial);const [question,setQuestion]=useState(initialQuestion||(initial==='own'?'':topics[initial].title));const [stage,setStage]=useState(0);
 const [prediction,setPrediction]=useState('');const [assist,setAssist]=useState(false);const [help,setHelp]=useState(false);
 const [hours,setHours]=useState(5);const [watts,setWatts]=useState(10);const [rate,setRate]=useState(31);
 const [thisMonth,setThisMonth]=useState(8200);const [lastMonth,setLastMonth]=useState(6500);const [choice,setChoice]=useState('');const [axis,setAxis]=useState('price');
 const [checks,setChecks]=useState<number[]>([]);const t=topics[topic];const Icon=t.icon;const cost=electricityCost(watts,hours,rate);
 return <div className="quest-screen"><button className="text-btn" onClick={stage?()=>setStage(stage-1):onBack}><ArrowLeft size={16}/> {stage?'一つ前へ':'やってみるに戻る'}</button>
 <Heading kicker="はるの探検" title={stage===0?'どんなことが気になった？':stage===1?'まずは、この3つから。':'予想と比べてみよう。'} sub="調べて、自分の考えを残したら、おうちの人に5ptをお願いできるよ。"/>
 <ol className="quest-progress">{['気になる！','やることを決める','調べて比べる','発見を残す'].map((x,i)=><li key={x} className={stage===i?'current':stage>i?'done':''}><span>{stage>i?<Check size={14}/>:i+1}</span>{x}</li>)}</ol>
 {stage===0&&<div className="quest-columns"><section className="panel"><div className="topic-icon"><Icon size={30}/></div><h2>{t.title}</h2><p>{t.lead}</p><label className="field">きみの疑問<input value={question} maxLength={100} onChange={e=>setQuestion(e.target.value)}/></label>
 {initial==='own'&&<fieldset><legend>どれに近い？</legend><div className="chips">{(['light','bill','drink','own'] as Topic[]).map(k=><button key={k} aria-pressed={topic===k} onClick={()=>setTopic(k)}>{k==='own'?'そのほか':topics[k].title}</button>)}</div></fieldset>}
 <label className="field">調べる前は、どう思う？<input placeholder={topic==='light'?'例：5時間で10円くらいかな':'「まだ分からない」でもいいよ'} value={prediction} maxLength={120} onChange={e=>setPrediction(e.target.value)}/></label>
 <Button onClick={()=>setStage(1)} disabled={!question.trim()||!prediction.trim()}>何からやるか、一緒に考える <ArrowLeft className="arrow-forward" size={18}/></Button></section>
 <aside className="panel tip-panel"><Tag>問いの見つけ方</Tag><h3>いつものことを、<br/>少しだけ立ち止まって。</h3><p>「いくら？」「どうして？」「変えたらどうなる？」をつけてみよう。</p><div className="question-note">夜、部屋の明かりを見て<br/><b>「これ、5時間でいくら？」</b></div><p>立派な質問じゃなくていい。きみが気になったことが、探検のはじまり。</p></aside></div>}
 {stage===1&&<section className="panel plan-panel"><Tag>きみの疑問</Tag><h2>「{question}」</h2><div className="assist-row"><label className="check-row"><input type="checkbox" checked={assist} onChange={e=>setAssist(e.target.checked)}/><Sparkles size={18}/>AIのお手伝い体験を見てみる</label><small>発表用の模擬AI・外部通信なし</small></div>
 {assist&&<div className="assistant-note"><Sparkles size={20}/><div><b>「{question}」なら、こんな順番はどう？</b><p>{topic==='light'?'まずは電球の数字を見つけよう。計算はそのあとで、一緒に試せるよ。':topic==='bill'?'いきなり節約しなくて大丈夫。まずは、おうちの人に今月と先月の金額を見せてもらおう。':topic==='drink'?'値段だけでなく、量も見てみよう。飲みきれるかも、きみが決める大切なことだよ。':'答えを一度に探さなくていいよ。聞く人や、見るものを一つ決めてみよう。'}</p><small>選んだ疑問の種類に合う、用意済みの手順を表示しています。</small></div></div>}
 <div className="task-cards">{t.steps.map((x,i)=><article key={x}><span className="step-number">0{i+1}</span><h3>{x}</h3><p>{i===0?'まず、ここから始めよう。':i===1?'数字を一つずつ確かめよう。':'正解よりも、きみの気づきを。'}</p></article>)}</div>
 <p className="safety-note">{topic==='light'?'電球は外さないでね。熱いところやコンセントには触らず、おうちの人と表示を見よう。':topic==='bill'?'請求書は、おうちの人と一緒に。名前や住所の写真は残さなくて大丈夫。':'本当に買わなくても探検できるよ。おうちの人と決めた範囲で試そう。'}</p>
 <Button onClick={()=>setStage(2)}>この順番でやってみる</Button></section>}
 {stage===2&&<div className="quest-columns"><section className="panel experiment"><Tag tone="amber">架空の数字で練習中</Tag><h2>{question}</h2><p className="prediction">調べる前の予想：{prediction}</p>
 {topic==='light'&&<><div className="number-inputs"><label>電球の表示（W）<input type="number" min="1" max="1500" value={watts} onChange={e=>setWatts(Math.max(1,Math.min(1500,Number(e.target.value))))}/></label><label>1kWhの料金（円）<input type="number" min="1" max="200" value={rate} onChange={e=>setRate(Math.max(1,Math.min(200,Number(e.target.value))))}/></label></div><label className="field range-label">つける時間 <b>{hours}時間</b><input type="range" min="1" max="24" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><div className="cost-result"><Lightbulb size={32}/><div><small>{hours}時間つけると</small><strong>{cost.toFixed(2)}<span>円</span></strong></div></div><p>Wは、同じ時間に使う電気の多さを表す数字だよ。</p><p>1時間なら {(watts*rate/1000).toFixed(2)}円。時間を変えると、どうなる？</p><details><summary>どうやって計算したの？</summary><p>{watts}W ÷ 1000 × {hours}時間 × {rate}円 = {cost.toFixed(2)}円</p><p>これは電球だけの練習用の計算。家全体の電気代や、実際の契約料金ではないよ。</p></details></>}
 {topic==='bill'&&<><div className="number-inputs"><label>先月の電気代（円）<input type="number" min="0" max="100000" value={lastMonth} onChange={e=>setLastMonth(Math.max(0,Math.min(100000,Number(e.target.value))))}/></label><label>今月の電気代（円）<input type="number" min="0" max="100000" value={thisMonth} onChange={e=>setThisMonth(Math.max(0,Math.min(100000,Number(e.target.value))))}/></label></div><div className="cost-result"><Zap size={32}/><div><small>先月と比べて</small><strong>{Math.abs(thisMonth-lastMonth).toLocaleString()}<span>円{thisMonth>=lastMonth?'多い':'少ない'}</span></strong></div></div><p>暑かった？ 家にいた時間が長かった？ 金額だけでは理由は分からないね。家族に聞いてみよう。</p><small>ここは架空の家の数字。家の請求書を入力する必要はありません。</small></>}
 {topic==='drink'&&<><div className="chips">{[['price','そのままの値段'],['unit','同じ量の値段'],['left','残るお金']].map(([k,v])=><button key={k} aria-pressed={axis===k} onClick={()=>setAxis(k)}>{v}</button>)}</div><div className="drink-options">{[{id:'A',name:'小さい飲み物',price:180,ml:200},{id:'B',name:'大きい飲み物',price:260,ml:400}].map(p=><button key={p.id} className={choice===p.name?'selected':''} onClick={()=>setChoice(p.name)} aria-pressed={choice===p.name}><ShoppingBag size={36}/><h3>{p.name}</h3><p>{p.ml}ml</p><strong>{axis==='unit'?p.price/p.ml*100:axis==='left'?300-p.price:p.price}円</strong><small>{axis==='unit'?'100mlあたり':axis==='left'?'300円から残るお金':'1本の値段'}</small></button>)}</div><button className="text-btn" aria-pressed={choice==='今日は買わない'} onClick={()=>setChoice('今日は買わない')}>今日は買わずに300円を残す{choice==='今日は買わない'?' ✓':''}</button></>}
 {topic==='own'&&<><label className="field">何を見た・誰に聞いた？<input value={choice} onChange={e=>setChoice(e.target.value)} maxLength={150} placeholder="例：おうちの人と値札を2つ比べた"/></label><p>一度で答えが出なくても大丈夫。「次はこれを知りたい」も発見だよ。</p></>}
 <button className="text-btn" onClick={()=>setHelp(!help)}><Lightbulb size={18}/>困ったら、ここを見てね</button>{help&&<div className="assistant-note"><p>{topic==='light'?'スライダーを1時間と5時間に動かしてみよう。何円変わった？':topic==='bill'?'今月と先月の数字を見て、多いのはどちら？ 家族に「何か違ったことはあった？」と聞いてみよう。':topic==='drink'?'「同じ量の値段」を押してみよう。安さと飲みきれる量、きみはどちらを大切にしたい？':'「見つけたこと」と「まだ分からないこと」を、一つずつ分けてみよう。'}</p></div>}</section>
 <aside className="panel"><h3>やってみたこと</h3><p>終わったところにチェック。</p>{t.steps.slice(0,2).map((step,i)=><label className="check-row task-check" key={step}><input type="checkbox" checked={checks.includes(i)} onChange={e=>setChecks(e.target.checked?[...checks,i]:checks.filter(x=>x!==i))}/>{step}</label>)}<small>発表では、この画面で架空の数字を比べてチェックできます。</small><Button disabled={checks.length<2||(topic==='drink'&&!choice)||(topic==='own'&&!choice.trim())} onClick={()=>onDone({title:question,prediction,choice:topic==='light'?hours+'時間で'+cost.toFixed(2)+'円（練習）':topic==='bill'?'今月'+thisMonth+'円・先月'+lastMonth+'円（練習）':choice,hint:topic==='light'?'時間を変えて、気づいたことは？':topic==='bill'?'金額を比べて、次に聞いてみたいことは？':'何を大切にして、その選び方にした？'})}>自分の発見を残す</Button><p className="quiet">ここで終わっても大丈夫。ポイントは記録を親に見てもらってから。</p></aside></div>}
 </div>;
}
