#!/usr/bin/env python3
"""Render a read-only navigation snapshot. Never modify task or approval sources."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ("current/WORKSTREAMS.json", "current/PROJECT_STATE.json", "current/TASKS.json")
STATUSES = {"done": "完了", "in_progress": "進行中", "blocked": "停止中", "awaiting_user_review": "レビュー待ち"}


def load_inputs(root):
    return [json.loads((root / path).read_text(encoding="utf-8")) for path in INPUTS]


def render(root=ROOT):
    config, state, ledger = load_inputs(root)
    if config["authority_mode"] != "navigation":
        raise ValueError("Unsupported authority mode: verify a Projects synchronization before switching")
    streams = config["workstreams"]
    by_id = {stream["id"]: stream for stream in streams}
    if len(by_id) != len(streams) or set(config["focus_order"]) != set(by_id) or len(config["focus_order"]) != len(streams):
        raise ValueError("Workstream IDs/focus order must be unique and complete")
    tasks = {task["id"]: task for task in ledger["tasks"]}
    fingerprint = hashlib.sha256()
    for path in INPUTS:
        fingerprint.update(path.encode("utf-8"))
        fingerprint.update((root / path).read_bytes())
    lines = ["# 今の現在地", "", "<!-- Generated by scripts/render_current.py; do not edit. -->",
             f"参照日：{config['updated_on']}（Asia/Shanghai）。元の製品状態更新：{state['updated_at']}。",
             f"入力hash：`{fingerprint.hexdigest()}`。オンラインのIssue／PR状態を取得した結果ではありません。", "",
             "## 今の目的", "", config["goal"], "",
             "## 並行している仕事", "", "| 系統 | 現在地の根拠 | 作業入口 |", "|---|---|---|"]
    issue_numbers = set()
    for stream_id in config["focus_order"]:
        stream = by_id[stream_id]
        for source in stream["sources"]:
            if not source.startswith("https://") and not (root / source).is_file():
                raise ValueError(f"Missing workstream source: {source}")
        descriptions = []
        for task_id in stream["task_ids"]:
            task = tasks[task_id]
            descriptions.append(f"{task_id}：{STATUSES.get(task['status'], task['status'])}")
        if stream_id == "validation":
            conducted = state["research_review"]["recruitment_materials"]["interviews_conducted"]
            descriptions.append("面談実施の記録あり（件数・結果はIssue確認）" if conducted else "面談未実施（既存状態ファイル）")
        elif stream_id == "pitch":
            descriptions.append("PR #2を都度確認（この表では状態を複製しない）")
        links = []
        for issue in stream["issues"]:
            if not isinstance(issue["number"], int) or issue["number"] < 1 or issue["number"] in issue_numbers:
                raise ValueError("Issue numbers must be unique positive integers")
            issue_numbers.add(issue["number"])
            links.append(f"[{issue['task_id']} / #{issue['number']}](https://github.com/saienjoy0/saitama-/issues/{issue['number']})")
        lines.append(f"| {stream['name']} | {'、'.join(descriptions)} | {'、'.join(links)} |")
    lines += ["", "## 次の作業と正本", ""]
    for index, stream_id in enumerate(config["focus_order"], 1):
        stream = by_id[stream_id]
        source_links = [f"[資料{i}]({path})" for i, path in enumerate(stream["sources"], 1)]
        lines.append(f"{index}. **{stream['name']}**：{stream['next_action']} {' / '.join(source_links)}")
        lines.append(f"   {stream['source_location']}")
    lines += ["", "## 本体の開始条件", "",
              f"本体：`{state['stage']}` / `{state['next_task_id']}`。implementation_allowed=`{str(state['implementation_allowed']).lower()}`。",
              "LP・発表見本への個別許可と、本体BUILD・実家庭公開・ライブAIの条件は分けます。Issueのcloseは承認ではありません。", "",
              "## 管理移行の現在地", "",
              "現在は入口整備の段階。既存タスク状態はTASKS、承認はPROJECT_STATE／REVIEW_BUNDLEが正本。Issueは作業と証拠への入口です。",
              "GitHub Projectは未設定。状態の正本切替・ネイティブ依存設定・自動同期は未実施です。",
              "更新：元データを変更して `python3 scripts/render_current.py`。検査：`python3 scripts/check_design_handoff.py`。",
              "[管理方式と次の移行](docs/workflow/PROJECT_MANAGEMENT.md) / [短い引継ぎ](docs/CODEX_HANDOFF.md)", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        output = render()
        target = ROOT / "CURRENT.md"
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != output:
                raise ValueError("CURRENT.md is stale; run python3 scripts/render_current.py")
            print("PASS: CURRENT.md matches navigation sources")
        else:
            target.write_text(output, encoding="utf-8")
            print("Updated CURRENT.md from navigation sources; approvals unchanged")
    except (KeyError, ValueError, OSError) as exc:
        raise SystemExit(f"FAIL: {exc}") from exc


if __name__ == "__main__":
    main()
